#!/bin/bash
set -e

# scripts/generate_directory_listings.sh
# Recursively generates index.html files for the repository directories
# to provide an FTP-like browsing experience on GitHub Pages.

REPO_ROOT="${1:-repo}"
# Remove trailing slash for consistency
REPO_ROOT="${REPO_ROOT%/}"

generate_index() {
    local dir="$1"
    # Ensure dir is relative to the current working directory for processing
    local rel_to_root="${dir#$REPO_ROOT}"
    rel_to_root="${rel_to_root#/}"
    
    local display_path="repo"
    [ -n "$rel_to_root" ] && display_path="repo/$rel_to_root"
    
    echo "Processing directory: $display_path"
    
    # Header
    cat <<EOF > "$dir/index.html"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Index of /$display_path</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; padding: 40px; line-height: 1.5; color: #24292e; }
        h1 { border-bottom: 1px solid #eaecef; padding-bottom: 0.3em; margin-top: 0; }
        hr { border: 0; border-top: 1px solid #eaecef; margin: 20px 0; }
        a { text-decoration: none; color: #0366d6; }
        a:hover { text-decoration: underline; }
        .file-list { list-style: none; padding: 0; }
        .file-list li { margin: 8px 0; display: flex; align-items: center; }
        .file-list li::before { margin-right: 10px; font-size: 18px; width: 24px; display: inline-block; text-align: center; }
        .file-list li.dir::before { content: "📁"; }
        .file-list li.file::before { content: "📄"; }
        .file-list li.back::before { content: "⬅️"; }
        .footer { margin-top: 40px; color: #6a737d; font-size: 12px; font-style: italic; border-top: 1px solid #eaecef; padding-top: 10px; }
    </style>
</head>
<body>
    <h1>Index of /$display_path</h1>
    <ul class="file-list">
EOF

    # Back link (if not at the very root of repo/)
    if [ -n "$rel_to_root" ]; then
        echo "        <li class=\"back\"><a href=\"../\">Parent Directory</a></li>" >> "$dir/index.html"
    fi

    # 1. Directories
    find "$dir" -mindepth 1 -maxdepth 1 -type d -not -path '*/.*' | sort | while read -r d; do
        name=$(basename "$d")
        echo "        <li class=\"dir\"><a href=\"$name/\">$name/</a></li>" >> "$dir/index.html"
    done

    # 2. Files
    find "$dir" -mindepth 1 -maxdepth 1 -type f -not -name "index.html" -not -name ".*" | sort | while read -r f; do
        name=$(basename "$f")
        echo "Found file: $name"
        echo "        <li class=\"file\"><a href=\"$name\">$name</a></li>" >> "$dir/index.html"
    done

    # Footer
    cat <<EOF >> "$dir/index.html"
    </ul>
    <div class="footer">Generated by Package Repository Manager on $(date)</div>
</body>
</html>
EOF
}

# Recursively generate indexes
DIRS_FILE=$(mktemp)
find "$REPO_ROOT" -type d -not -path '*/.*' > "$DIRS_FILE"

while read -r directory; do
    generate_index "$directory"
done < "$DIRS_FILE"

rm "$DIRS_FILE"
