#!/bin/bash
set -e

# scripts/generate_directory_listings.sh
# Recursively generates index.html files for the repository directories
# to provide an FTP-like browsing experience on GitHub Pages.

REPO_ROOT="${1:-repo}"

generate_index() {
    local dir="$1"
    local rel_path="${dir#$REPO_ROOT}"
    rel_path="${rel_path#/}"
    
    # Human-friendly path for the title
    local display_path="repo"
    [ -n "$rel_path" ] && display_path="repo/$rel_path"
    
    echo "Generating index for $display_path..."
    
    cat <<EOF > "$dir/index.html"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Index of /$display_path</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif; padding: 40px; line-height: 1.5; color: #24292e; }
        h1 { border-bottom: 1px solid #eaecef; padding-bottom: 0.3em; }
        hr { border: 0; border-top: 1px solid #eaecef; margin: 20px 0; }
        a { text-decoration: none; color: #0366d6; }
        a:hover { text-decoration: underline; }
        .file-list { list-style: none; padding: 0; }
        .file-list li { margin: 8px 0; display: flex; align-items: center; }
        .file-list li::before { margin-right: 10px; font-size: 18px; }
        .file-list li.dir::before { content: "📁"; }
        .file-list li.file::before { content: "📄"; }
        .footer { margin-top: 40px; color: #6a737d; font-size: 12px; font-style: italic; }
    </style>
</head>
<body>
    <h1>Index of /$display_path</h1>
    <hr>
    <ul class="file-list">
        <li class="dir"><a href="../">../</a></li>
EOF

    # Directories (excluding hidden ones and those that might be created by the process)
    find "$dir" -mindepth 1 -maxdepth 1 -type d -not -path '*/.*' | sort | while read -r d; do
        name=$(basename "$d")
        echo "        <li class=\"dir\"><a href=\"$name/\">$name/</a></li>" >> "$dir/index.html"
    done

    # Files (excluding index.html and hidden files)
    find "$dir" -mindepth 1 -maxdepth 1 -type f -not -name "index.html" -not -name ".*" | sort | while read -r f; do
        name=$(basename "$f")
        echo "        <li class=\"file\"><a href=\"$name\">$name</a></li>" >> "$dir/index.html"
    done

    cat <<EOF >> "$dir/index.html"
    </ul>
    <hr>
    <div class="footer">Generated by Package Repository Manager on $(date)</div>
</body>
</html>
EOF
}

# Ensure we are working with an absolute path if possible or relative to root
[ -d "$REPO_ROOT" ] || { echo "Error: Directory $REPO_ROOT not found"; exit 1; }

# Recursively generate indexes
find "$REPO_ROOT" -type d -not -path '*/.*' | while read -r directory; do
    generate_index "$directory"
done
